### ISSUE TITLE
where are detailed instructions referred to

### ISSUE THREAD

**Issue by mildmanjan** [NoxxGames/AwsGameLift-5.0-for-UE5-5.1#1]
Hi
"For more detailed instructions on how to build the c++ SDK, please refer to the README.md file located in the c++ SDK directory." _I cant find this file - maybe a stupid question but can I just place these files in my UE5 plugins folder, change the .cpp and uproject file and it should work or do I still need to build with cmake? thanks!

**Comment by mildmanjan** [comment]
nvm found them in the downloaded file :)

**Comment by NoxxGames** [comment]
Hi,

Sorry for the confusion, I've added an instruction on how to install in the main README for this repo. You won't need to build anything yourself, just adding the GameLiftServerSDK folder to your projects/engines plugin folder :)
